package com.timsm.demo.dto;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@Builder
@ToString
public class SalaryDTO {
    private String payYm;
    private String empNo;
    private Long supply01;
    private Long supply02;
    private Long supply03;
    private Long supply04;
    private Long supply05;
    private Long supply06;
    private Long supply07;
    private Long supply08;
    private Long supply09;
    private Long supply10;
    private Long supply11;
    private Long supply12;
    private Long supply13;
    private Long supply14;
    private Long supply15;
    private Long supply16;
    private Long supply17;
    private Long supply18;
    private Long supply19;
    private Long supply20;
    private Long supply21;
    private Long supply22;
    private Long supply23;
    private Long supply24;
    private Long supply25;
    private Long supply26;
    private Long supply27;
    private Long supply28;
    private Long supply29;
    private Long supply30;
    private Long supply31;
    private Long supply32;
    private Long supply33;
    private Long supply34;
    private Long supply35;
    private Long supply36;
    private Long supply37;
    private Long supply38;
    private Long supply39;
    private Long supply40;
    private Long supply41;
    private Long supply42;
    private Long supply43;
    private Long supply44;
    private Long supply45;
    private Long supply46;
    private Long supply47;
    private Long supply48;
    private Long supply49;
    private Long supply50;
    private Long supply51;
    private Long supply52;
    private Long supply53;
    private Long supply54;
    private Long supply55;
    private Long payAmt;
    private Long deduct01;
    private Long deduct02;
    private Long deduct03;
    private Long deduct04;
    private Long deduct05;
    private Long deduct06;
    private Long deduct07;
    private Long deduct08;
    private Long deduct09;
    private Long deduct10;
    private Long deduct11;
    private Long deduct12;
    private Long deduct13;
    private Long deduct14;
    private Long deduct15;
    private Long deduct16;
    private Long deduct17;
    private Long deduct18;
    private Long deduct19;
    private Long deduct20;
    private Long deduct21;
    private Long deduct22;
    private Long deduct23;
    private Long deduct24;
    private Long deduct25;
    private Long deduct26;
    private Long deduct27;
    private Long deduct28;
    private Long deductAmt;
    private String workCnt;
    private String workAmCnt;
    private String workPmCnt;
    private Double extenCnt;
    private Double midntCnt;
    private Double holiCnt;
    private int timePay;
    private Double workTimeCnt;
    private int holiAmDay;
    private int holiPmDay;
}
