spring.application.name=demo

# 오라클 DB 연결 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@121.176.0.167:1521:TYIIS
spring.datasource.username=kduser
spring.datasource.password=kduser

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
# logging.level.com.timsm.demo.mapper=DEBUG